# Generated by Django 3.2.13 on 2024-07-18 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IMSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imsi', models.CharField(max_length=15, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imsis', to='contact.contact')),
            ],
        ),
        migrations.CreateModel(
            name='IMEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imeis', to='contact.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondent', models.CharField(max_length=15)),
                ('duration', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('imei', models.CharField(max_length=15)),
                ('site_name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('imsi', models.CharField(max_length=15)),
                ('communication_type', models.CharField(choices=[('SMS', 'SMS'), ('Call', 'Call')], max_length=4)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='contact.contact')),
            ],
        ),
    ]
