# Generated by Django 3.2.13 on 2024-07-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20240723_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='communication_type',
            field=models.CharField(choices=[('call_in', 'Appel Entrant'), ('call_out', 'Appel Sortant'), ('sms_in', 'SMS Entrant'), ('sms_out', 'SMS Sortant')], max_length=9),
        ),
        migrations.AlterField(
            model_name='communication',
            name='correspondent',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='communication',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='communication',
            name='imei',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='communication',
            name='imsi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='communication',
            name='locality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='communication',
            name='site_name',
            field=models.CharField(max_length=255),
        ),
    ]
